network:
  version: 1
  config:
    - type: physical
      name: Ethernet Instance 0
      mac_address: {{ .mac }}
      subnets:
        - type: static
          address: {{ .cidr }}
          # netmask: 255.255.255.192
          dns_nameservers:
            - 8.8.8.8
            - 8.8.4.4
      mtu: {{ .mtu }}
